### ISSUE TITLE
Element in dropdown menu not found

### ISSUE THREAD

**Issue by Jteve-Sobs** [licanhua/YWinAppDriver#14]
Hi,

appreciate your work and I would like to use YWinAppDriver in my project.

In my project I just replaced the WinAppDriver and gave it a go.
However when selecting an entry in a dropdown menu (which was opened in a previous click) this error occurs:
"Didn't found the element in cache" and the program fails.
While debugging the value of the variable is not null, as seen in this if statement where the error is thrown:
`if (element != null)  `
`{  `
  `element.Click();  // error occurs here  `
`}`

Is it also possible to implement the screenshot feature of Selenium ? Would be very helpful.

Best regards and thanks

**Comment by licanhua** [comment]
Are you using the newest version? I didn't see below code. 

```
if (element != null)
{
element.Click();
}
```

For the menu, if you open it and close it, although the name is the same, you need to locate the element again.
To reduce the cache size, the logic is like this:
1. You located a element, and YWinAppDrive cached it. YWinAppDriver hold an reference to the UIA element
2. The element changed(like you close the menu, then open again). The actual UIA element is changed too although it looks like the same
3. You use the old reference to click, then YWinAppDriver report Stale Element and remove the element from the cache
4. If you use the old reference to click again, then YWinAppDriver report 'Didn't found the element in cache'

**Comment by licanhua** [comment]
I already added the screenshot feature

**Comment by licanhua** [comment]
@Jteve-Sobs did you still see the problem in latest version?
