### ISSUE TITLE
Unable to create session with attachToTopLevelWindowClassName

### ISSUE THREAD

**Issue by shoaibmansoor** [licanhua/YWinAppDriver#21]
`app` property should not be required when the user provides a native window handle for creating a session.

I am getting the following error message:
{"error":"SessionNotCreateException","message":"JsonSerializationException: Cannot write a null value for property 'app'. Property requires a non-null value. Path 'desiredCapabilities'."

![image](https://user-images.githubusercontent.com/36887168/108998420-e7d48980-76c6-11eb-9ae5-b97f568d0258.png)

**Comment by licanhua** [comment]
Are you trying to use appium, but you didn't use actually Appium.

You need to have capability like this:
{
   "app": "Root",
   "attachToTopLevelWindowClassName": "???"
}
YWinAppDriver doesn't understand "appium:attachToTopLevelWindowClassName", and expect appium to remove the appium: prefix
