### ISSUE TITLE
/touch/down is not implemented

### ISSUE THREAD

**Issue by shoaibmansoor** [licanhua/YWinAppDriver#22]
Getting response code 500 with an error message: `The method or operation is not implemented.`

![image](https://user-images.githubusercontent.com/22621280/109000629-f6707000-76c9-11eb-8a90-cbc37264dd83.png)

**Comment by licanhua** [comment]
I guess the driver have problem to support MultiTouch, so I removed multitouch.
You should not hit this anymore.
