### ISSUE TITLE
Question: does this project requires developer mode like WinAppDriver?

### ISSUE THREAD

**Issue by wyhmichael** [licanhua/YWinAppDriver#23]
Hi there, this is just a quick question: WinAppDriver project mentioned about developer mode at https://github.com/Microsoft/WinAppDriver#install--run-winappdriver, does this project require the same set up?

**Comment by licanhua** [comment]
I think neither of them required the developer mode.
You often need to enable developer mode when you deploy your test app

**Comment by wyhmichael** [comment]
Thanks @licanhua for the quick response 👍

**Comment by Jteve-Sobs** [comment]
WinAppDriver needs the developer mode. Without it WinAppDriver can't even be launched. Could be different with your program.
