### ISSUE TITLE
Nothing appears in the WinAppdriver.exe console window when executing the window

### ISSUE THREAD

**Issue by anunay1** [licanhua/YWinAppDriver#3]
I executed the calculator test but nothing appears in the console window when the tests are executed. Is it expected.

**Comment by licanhua** [comment]
Yes. I didn't provide log function yet

**Comment by anunay1** [comment]
It will be a good idea to log the same to a file and also I observed that the execution is slow

**Comment by licanhua** [comment]
You are right. Log is important.
I also notice the `slow`. I didn't implement the cache for search yet. actually WinUI cached by class/name and others

**Comment by licanhua** [comment]
Thanks to report this issue. now the performance problem is fixed.
I added the cache, also changed the click action to invoke.

**Comment by anunay1** [comment]
Thanks will test it and let you know

**Comment by anunay1** [comment]
And verified that the logs are displayed on the console, but is there any log file that gets generated.

**Comment by licanhua** [comment]
no. but easy for you if you are using powershell to tee the output to a file, also show output in console.

PS C:\repo\YWinAppDriver\src\WinAppDriver\bin\Debug\netcoreapp3.1>` .\WinAppDriver.exe --urls http://127.0.0.1:4723 |tee -filepath test.out`

**Comment by licanhua** [comment]
I just add code to generate logs to Logs/WinAppDriver-{Date}.txt
Please pay attention that if you are running from VS, there is no log files. You can remove this restriction by

```
      if (env.IsDevelopment())
      {
        app.UseDeveloperExceptionPage();
      }
      else
      {
        loggerFactory.AddFile("Logs/WinAppDriver-{Date}.txt");
      }
```

**Comment by anunay1** [comment]
Thanks will check that
